### ISSUE TITLE
Unable to use Swarm after most recent update

### ISSUE THREAD

**Issue by springthomas** [mcmonkeyprojects/SwarmUI#879]
### Expected Behavior

When I start swarmui, I should be able to generate an image when I click generate. 

### Actual Behavior

When I click generate, I am told "no backends available" Swarm was working fine an hour ago, before the update.

### Steps to Reproduce

I open swarmui, I click generate. I am told no backends available. I click update and restart. I click generate, I am told no backends available. 

### Debug Logs

https://paste.denizenscript.com/View/134640

### Other

multiple people have this issue

**Comment by AshtakaOOf** [comment]
Duplicate of #878

**Comment by mcmonkey4eva** [comment]
You appear to both have the issue ashtaka linked above, and also a separate boot issue where numpy is failing to install?
(Side note, you also have a ton of warnings about invalid model names in your log, you should probably look that over and clean it up. Avoid symbols like `,` direct in a filename).

I'm not sure why your system appears to want mesonpy, but it's not available? Weird, but I added an autoinstaller to correct for tha.t
Hit Server -> Update&Restart, it should fix itself now

**Comment by springthomas** [comment]
Issue is still persisting, I have thrown another log in. 

https://paste.denizenscript.com/View/134646

While I would like this fixed, I am pleased to say that a fresh install of swarm works flawlessly.

**Comment by mcmonkey4eva** [comment]
OH. I see what happened: you had one of the blackwell nightly installs of the comfy backend, with python 3.13 and experimental stuff in the lib. Yeah a reinstall now that blackwell is in stable is probably the best thing here.
